services:
  container-api:
    image: ghcr.io/geoffsee/container-api:stable
    build:
      dockerfile: crates/container-api/Dockerfile
      context: .
    container_name: container-api
    environment:
      - SERVICE_REGISTRY_URL=http://service-registry:3003
    ports:
      - "3001:3000"
    networks:
      - coreos-net
    depends_on:
      - service-registry
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
        reservations:
          cpus: "0.25"
          memory: 512m

  repl-api:
    image: ghcr.io/geoffsee/repl-api:stable
    build:
      dockerfile: crates/repl-api/Dockerfile
      context: .
    container_name: repl-api
    environment:
      - SERVICE_REGISTRY_URL=http://service-registry:3003
    ports:
      - "3002:3001"
    networks:
      - coreos-net
    depends_on:
      - service-registry
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
        reservations:
          cpus: "0.25"
          memory: 512m

  coreos:
    image: ghcr.io/geoffsee/fedora-coreos:stable
    build:
      dockerfile: Containerfile
      context: coreos-components/coreos
    container_name: coreos
    privileged: true
    ports:
      - "8085:8085"
    cgroup_parent: "coreos.slice"
    cgroup: "private"
    # Start systemd properly to enable podman and other services
    command: ["/sbin/init"]
    volumes:
      - sandbox-data:/data/sandbox
    networks:
      - coreos-net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2g
        reservations:
          cpus: "0.5"
          memory: 1g

  coreos-etcd:
    image: ghcr.io/geoffsee/etcd:stable
    build:
      dockerfile: Containerfile
      context: coreos-components/etcd
    container_name: coreos-etcd
    cgroup_parent: "coreos.slice"
    cgroup: "private"
    networks:
      - coreos-net
    command: [
      "etcd",
      "--name", "s1",
      "--data-dir", "/etcd-data",
      "--advertise-client-urls", "http://0.0.0.0:2379",
      "--listen-client-urls", "http://0.0.0.0:2379",
      "--initial-advertise-peer-urls", "http://0.0.0.0:2380",
      "--listen-peer-urls", "http://0.0.0.0:2380",
      "--initial-cluster", "s1=http://0.0.0.0:2380",
      "--initial-cluster-state", "new",
      "--initial-cluster-token", "etcd-cluster-1"
    ]
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd-data:/etcd-data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512m
        reservations:
          cpus: "0.1"
          memory: 256m

  service-registry:
    image: ghcr.io/geoffsee/service-registry:stable
    build:
      dockerfile: crates/service-registry/Dockerfile
      context: .
    container_name: service-registry
    environment:
      ETCD_ENDPOINTS: "coreos-etcd:2379"
      COREOS_URL: "http://coreos:8085"
    ports:
      - "3003:3003"
    networks:
      - coreos-net
    depends_on:
      coreos-etcd:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512m
        reservations:
          cpus: "0.1"
          memory: 256m

  registry:
    image: ghcr.io/geoffsee/registry:stable
    build:
      dockerfile: Containerfile
      context: coreos-components/registry
    container_name: registry
    ports:
      - "5001:5000"
    networks:
      - coreos-net
    volumes:
      - registry-data:/var/lib/registry
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
        reservations:
          cpus: "0.25"
          memory: 512m

  supervisor:
    image: ghcr.io/geoffsee/supervisor:stable
    build:
      dockerfile: crates/supervisor/Dockerfile
      context: .
    container_name: supervisor
    environment:
      - SERVICE_REGISTRY_URL=http://service-registry:3003
    ports:
      - "3004:3000"
    networks:
      - coreos-net
    depends_on:
      - service-registry
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512m
        reservations:
          cpus: "0.1"
          memory: 256m
volumes:
  etcd-data:
  sandbox-data:
  registry-data:

networks:
  coreos-net:
